# frozen_string_literal: true

source "http://rubygems.org"
ruby File.read(".ruby-version").chomp

gem "aws-sdk-cloudwatch", "~>1.47"

group :test do
  gem "rspec"
  gem "timecop"
  gem "webmock"
end
