# frozen_string_literal: true

source "http://rubygems.org"
ruby File.read(".ruby-version").chomp

gem "aws-sdk-cloudwatch", "~>1.99.0"
gem "sequel", "~> 5.83.0"
gem "mysql2", "~> 0.5.6"

group :test do
  gem "rspec"
  gem "timecop"
  gem "webmock"
end

group :production do
  gem "sentry-ruby"
end
