version: 0.2

env:
  variables:
    TF_IN_AUTOMATION: true
    TF_INPUT: 0
    AWS_REGION: eu-west-2
  parameter-store:
    DOCKER_USERNAME: "/moj-network-access-control/docker/username"
    DOCKER_PASSWORD: "/moj-network-access-control/docker/password"

phases:

  build:
    commands:
      - make authenticate-docker
      - make test
