version: 0.2

env:
  variables:
    DB_PORT: 3306
  parameter-store:
    REGISTRY_URL: "/codebuild/dhcp/$ENV/ecr/endpoint"
    TARGET_AWS_ACCOUNT_ID: "/codebuild/$ENV/account_id"

phases:
  install:
    commands:
      - echo nope

  build:
    commands:
      - make deploy
