version: "3"
services:
  dhcp_config:
    image: nginx:alpine
    volumes:
      - ${PWD}/dhcp-service/config.json:/usr/share/nginx/html/config.json
    ports:
      - 80:80
  dhcp:
    build: ./dhcp-service
    depends_on:
      - dhcp_config
      - db
    environment:
      INTERFACE: eth0
      DB_NAME: kea
      DB_USER: kea
      DB_PASS: kea
      DB_HOST: db
      DB_PORT: 3306
      KEA_CONFIG_URL: "http://dhcp_config:80/config.json"
    ports:
      - 67:67
      - 68:68
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
      MYSQL_DATABASE: kea
    ports:
    - 3306:3306
volumes:
  db_data: {}
