version: "3"
services:
  dhcp:
    build: ./dhcp-service
    depends_on:
      - db
    environment:
      INTERFACE: eth0
      DB_NAME: kea
      DB_USER: kea
      DB_PASS: kea
      DB_HOST: db
      DB_PORT: 3306
      LOCAL_DEVELOPMENT: "true"
    ports:
      - 67:67/udp
      - 8000:8000
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/stats/:/stats

  dhcp-test:
    build:
      context: ./dhcp-service
      args:
        BUNDLE_CONFIG: ""
    depends_on:
      - db
      - dhcp
    ports:
      - 68:68/udp
    volumes:
      - ./dhcp-service/dhcp_test.sh:/dhcp_test.sh
      - ./dhcp-service/stats/:/stats

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
      MYSQL_DATABASE: kea
    ports:
    - 3306:3306

volumes:
  db_data: {}

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.0/24"
