version: "3"
services:
  dhcp-primary:
    build:
      context: ./dhcp-service
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    depends_on:
      - db
    environment:
      INTERFACE: eth0
      DB_HOST: db
      DB_PORT: 3306
      SERVER_NAME: "primary"
    env_file: .env
    ports:
      - 67:67/udp
      - 8000:8000
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/metrics/:/metrics
    networks:
      default:
        ipv4_address: ${PRIMARY_IP}

  dhcp-standby:
    build:
      context: ./dhcp-service
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    environment:
      INTERFACE: eth0
      DB_HOST: db
      DB_PORT: 3306
      SERVER_NAME: "standby"
    env_file: .env
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/metrics/:/metrics
    networks:
      default:
        ipv4_address: ${STANDBY_IP}

  dhcp-api:
    build:
      context: ./dhcp-service
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
    environment:
      INTERFACE: eth0
      DB_HOST: db
      DB_PORT: 3306
      SERVER_NAME: "api"
    env_file: .env
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/metrics/:/metrics

  dhcp-test:
    build:
      context: ./dhcp-service
      args:
        SHARED_SERVICES_ACCOUNT_ID: "${SHARED_SERVICES_ACCOUNT_ID}"
        EXTRA_BUNDLE_CONFIG: ""
    environment:
      INTERFACE: eth0
      DB_HOST: db
      DB_PORT: 3306
    env_file: .env
    depends_on:
      - db
      - dhcp-primary
    ports:
      - 68:68/udp
    volumes:
      - ./dhcp-service/dhcp_test.sh:/dhcp_test.sh
      - ./dhcp-service/metrics/:/metrics

  db:
    image: "${SHARED_SERVICES_ACCOUNT_ID}.dkr.ecr.eu-west-2.amazonaws.com/dhcp-mysql:mysql-5-7"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
    - 3306:3306

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.0/24"
