version: "3"
services:
  dhcp-primary:
    platform: linux/amd64
    build:
      context: ./dhcp-service
    depends_on:
      db:
        condition: service_healthy
    environment:
      INTERFACE: eth0
      DB_NAME: kea
      DB_USER: root
      DB_PASS: password
      DB_HOST: db
      DB_PORT: 3306
      LOCAL_DEVELOPMENT: "true"
      SERVER_NAME: "primary"
      PRIMARY_IP: "172.1.0.10"
      STANDBY_IP: "172.1.0.11"
      PUBLISH_METRICS: "true"
      METRICS_NAMESPACE: "Kea-DHCP"
    ports:
      - 67:67/udp
      - 8000:8000
    healthcheck:
      test: bash -c "[ -f /tmp/kea_started ]"
      timeout: 20s
      retries: 10
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/metrics/:/metrics
    networks:
      default:
        ipv4_address: 172.1.0.10

  dhcp-standby:
    platform: linux/amd64
    build:
      context: ./dhcp-service
    environment:
      INTERFACE: eth0
      DB_NAME: kea
      DB_USER: kea
      DB_PASS: kea
      DB_HOST: db
      DB_PORT: 3306
      LOCAL_DEVELOPMENT: "true"
      SERVER_NAME: "standby"
      PRIMARY_IP: "172.1.0.10"
      STANDBY_IP: "172.1.0.11"
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/metrics/:/metrics
    networks:
      default:
        ipv4_address: 172.1.0.11

  dhcp-api:
    platform: linux/amd64
    build:
      context: ./dhcp-service
    environment:
      INTERFACE: eth0
      DB_NAME: kea
      DB_USER: kea
      DB_PASS: kea
      DB_HOST: db
      DB_PORT: 3306
      LOCAL_DEVELOPMENT: "true"
      SERVER_NAME: "api"
      PRIMARY_IP: "172.1.0.10"
      STANDBY_IP: "172.1.0.11"
    volumes:
      - $HOME/.aws/credentials:/root/.aws/credentials:ro
      - ./dhcp-service/metrics/:/metrics

  dhcp-test:
    platform: linux/amd64
    build:
      context: ./dhcp-service
      dockerfile: Dockerfile.test
      args:
        EXTRA_BUNDLE_CONFIG: ""
    environment:
      DB_NAME: kea
      DB_USER: kea
      DB_PASS: kea
      DB_HOST: db
      DB_PORT: 3306
      METRICS_NAMESPACE: "Kea-DHCP"
    depends_on:
      db:
        condition: service_healthy
      dhcp-primary:
        condition: service_healthy
    ports:
      - 68:68/udp
    volumes:
      - ./dhcp-service/metrics/:/test/metrics
      - ./dhcp-service/spec/:/test/spec

  db:
    image: "mysql:8.0.27"
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: kea
      MYSQL_PASSWORD: kea
      MYSQL_DATABASE: kea
    ports:
      - 3306:3306
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-uroot", "-ppassword" ]
      timeout: 20s
      retries: 10

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: "172.1.0.0/24"
