FROM ruby:2.7.2-alpine3.13

ARG EXTRA_BUNDLE_CONFIG="without 'test'"

RUN apk add bash build-base curl mysql mysql-client mysql-dev && \
  curl -1sLf 'https://dl.cloudsmith.io/public/isc/kea-2-1/setup.alpine.sh' | bash && \
  apk update &&  \
  apk upgrade && \
  apk add isc-kea-perfdhcp && \
  rm -rf /var/cache/apk/*

COPY ./metrics ./metrics

RUN cd metrics && \
  bundle config set no-cache 'true' ${EXTRA_BUNDLE_CONFIG} && \
  bundle install
