{
 "title": "KEA DHCP Server",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "metricName": "pkt4-offer-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-offer-sent", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-ack-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-ack-sent", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-decline-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-discover-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-sent", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-inform-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-nak-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-nak-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-parse-failed", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-receive-drop", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-release-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-request-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "pkt4-unknown-received", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "reclaimed-declined-addresses", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "reclaimed-leases", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "DHCP Subnet Pools",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "id": "assigned_addresses",
     "metricName": "total-addresses",
     "namespace": "Kea-DHCP-Server",
     "region": "eu-west-2",
     "statistics": [ "Maximum" ]
    },
    { "metricName": "assigned-addresses", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Maximum" ] },
    { "metricName": "cumulative-assigned-addresses", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "declined-addresses", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "reclaimed-declined-addresses", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] },
    { "metricName": "reclaimed-leases", "namespace": "Kea-DHCP-Server", "region": "default", "statistics": [ "Average" ] }
   ]
  },
  {
   "title": "Cluster Resources",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "id": "cpu_utilization",
     "metricName": "CPUUtilization",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "id": "network_tx_bytes",
     "metricName": "NetworkTxBytes",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "metricName": "TaskSetCount",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "metricName": "StorageWriteBytes",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "metricName": "MemoryUtilized",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "metricName": "DeploymentCount",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "metricName": "DesiredTaskCount",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    },
    {
     "dimensions": {
      "ClusterName": "staff-device-production-dhcp-cluster"
     },
     "metricName": "NetworkRxBytes",
     "namespace": "ECS/ContainerInsights",
     "region": "eu-west-2",
     "statistics": [ "Average" ]
    }
   ]
  }
 ]
}